export enum DialogRoles {
    CANCEL = 'CANCEL',
    DELETE_EXERCISE = 'DELETE_EXERCISE',
    DELETE_TRAINING = 'DELETE_TRAINING',
    SELECT_DATE = 'SELECT_DATE',
    REORDER_EXERCISES = 'REORDER_EXERCISES',
    CHANGE_SET_CATEGORY = 'CHANGE_SET_CATEGORY',
}
